### ISSUE TITLE
Update AspNetCore to 2.0.3 jsreport binary 1.9.2 and local 1.1.0 no longer displays pdf

### ISSUE THREAD

**Issue by ksspittctync** [jsreport/jsreport-dotnet#9]
ASPNET Core project that was installed with the Nuget packages for jsreport using Visual Studio Nuget Package Manager:
Microsoft.AspNetCore.All (2.0.0)
Jsreport.AspNetCore (1.0.0)
Jsreport.Binary (1.8.2)
Jsreport.Local (1.0.1)

Updated the Nuget packages using Visual Studio Nuget Package Manager and now have the following:
Microsoft.AspNetCore.All (2.0.3)
Jsreport.AspNetCore (1.0.0)
Jsreport.Binary (1.9.2)
Jsreport.Local (1.1.0)

Can no longer display PDF from Razor pages.  Now when I attempt to run the debug, I get the following error:
An unhandled exception occurred while processing the request.
MissingMethodException: Method not found: 'Void jsreport.Types.DebugOptions.set_LogsToResponse(Boolean)'.
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder+<>c+<<BuildPipeline>b__8_0>d.MoveNext()

I have noticed that in my user folder for .jsreport still shows the following folder:
binary-default-1.8.2.0

Was this folder suppose to update?  Would this be related to the issue and how do I fix?
 
Running on Windows 10, with VS2017 version 15.4.4

**Comment by pofider** [comment]
Thank you for the problem description.
I don't know what is the problem at the first glance, but will try to find a time to look into it.

**Comment by pofider** [comment]
I've released hotfix for `jsreport.AspNetCore`. Please update it and the debug should work for you.

You should be able to find `jsreport.exe` in 
c:\Users\xxx\AppData\Local\Temp\jsreport\dotnet\binary-default-1.9.2.0\

**Comment by ksspittctync** [comment]
Was able to find jsreport.exe in
 c:\Users\xxx\AppData\Local\Temp\jsreport\dotnet\binary-default-1.9.2.0\
Updated jsreport.AspNetCore from v1.0.0 to v1.0.1, but still getting an error:
An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder+<>c+<<BuildPipeline>b__8_0>d.MoveNext()

**Comment by pofider** [comment]
Please paste the whole stack trace.
Or even better, create a sample minimal repository replicating the issue so I can take a look on it.
Thank you.

**Comment by ksspittctync** [comment]
Have determined that 2nd error was related to use of corporate proxy server requiring NTLM authentication using an NTLM / NTLM Session Response / NTLMv2 authenticating HTTP proxy.

Used your original download example for jsreport for aspnetcore, jsreport-dotnet-example-webapp-master, updated the Nuget packages, deactivated the authenticating HTTP proxy, and the example works.

However, if the authenticating HTTP proxy remains activated, the following stack trace is produced for the download example with updated Nuget packages:
jsreport.Local.JsReportBinaryException: Error rendering report: instance has been daemonized and initialized successfully (pid: 1200)Error: An error occurred while trying to execute the command:    at onCriticalError ([eval]:36106:25)    at [eval]:36061:13    at tryCatcher ([eval]:9718:23)    at Promise._settlePromiseFromHandler ([eval]:38241:31)    at Promise._settlePromise ([eval]:38298:18)    at Promise._settlePromise0 ([eval]:38343:10)    at Promise._settlePromises ([eval]:38418:18)    at Async._drainQueue ([eval]:4650:16)    at Async._drainQueues ([eval]:4660:10)    at Immediate.Async.drainQueues [as _onImmediate] ([eval]:4534:14)    at processImmediate [as _immediateCallback] (timers.js:396:17) {"originalError":{}}(Original) Error: Invalid protocol: localhost:    at Request.init ([eval]:48876:31)    at new Request ([eval]:48545:8)    at request ([eval]:47078:10)    at Function.post ([eval]:47086:12)    at Client.render ([eval]:39123:32)    at [eval]:36137:71    at Promise._execute ([eval]:5433:9)    at Promise._resolveFromExecutor ([eval]:38212:18)    at new Promise ([eval]:37808:14)    at startRender ([eval]:36119:10)    at [eval]:36031:15    at tryCatcher ([eval]:9718:23)    at Promise._settlePromiseFromHandler ([eval]:38241:31)    at Promise._settlePromise ([eval]:38298:18)    at Promise._settlePromise0 ([eval]:38343:10)    at Promise._settlePromises ([eval]:38422:18)    at Async._drainQueue ([eval]:4650:16)    at Async._drainQueues ([eval]:4660:10)    at Immediate.Async.drainQueues [as _onImmediate] ([eval]:4534:14)    at processImmediate [as _immediateCallback] (timers.js:396:17) {}
   at jsreport.Local.Internal.LocalUtilityReportingService.<RenderAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at jsreport.AspNetCore.JsReportMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()


Using my application, with the authenticating HTTP proxy remaining active, the following stack trace is produced:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Internal.MiddlewareFilterBuilder.<>c.<<BuildPipeline>b__8_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at jsreport.AspNetCore.JsReportMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by pofider** [comment]
A lot has changed in the jsreport v3 sdk, please test it there and come back if you have still troubles.
